CREATE TABLE [dbo].[Blogs]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(MAX) NULL,
	[ShortDescription] NVARCHAR(MAX) NULL,
	[HeaderImageId] UNIQUEIDENTIFIER NULL,
	[Views] INT NOT NULL,
	[InsertedBy] UNIQUEIDENTIFIER NOT NULL,
	[InsertedDate] DATETIME NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NULL,
	[LastEditedDate] DATETIME NULL,
	[IsDeleted] BIT NULL,
	[DeletedBy] UNIQUEIDENTIFIER NULL,
	[DeletedDate] DATETIME NULL

	CONSTRAINT PK_Blogs_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90),
	CONSTRAINT FK_Blogs_HeaderImageId FOREIGN KEY(HeaderImageId) REFERENCES Documents(Id)
)
