CREATE TABLE [dbo].[BlogFragments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[BlogEntityId] UNIQUEIDENTIFIER NOT NULL,
	[ImageId] UNIQUEIDENTIFIER NULL,
	[ImageTitle] NVARCHAR(MAX) NULL,
	[ImageDescription] NVARCHAR(MAX) NULL,
	[Order] INT NOT NULL,
	[SubTitle] NVARCHAR(MAX) NULL,
	[Content] NVARCHAR(MAX) NULL,
	[InsertedBy] UNIQUEIDENTIFIER NOT NULL,
	[InsertedDate] DATETIME NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NULL,
	[LastEditedDate] DATETIME NULL,
	[IsDeleted] BIT NULL,
	[DeletedBy] UNIQUEIDENTIFIER NULL,
	[DeletedDate] DATETIME NULL

	CONSTRAINT PK_BlogFragments_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90),
	CONSTRAINT FK_BlogFragments_BlogEntityId FOREIGN KEY(BlogEntityId) REFERENCES Blogs(Id),
	CONSTRAINT FK_BlogFragments_ImageId FOREIGN KEY(ImageId) REFERENCES Documents(Id)
)
