CREATE TABLE [dbo].[BlogLikes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[BlogEntityId] UNIQUEIDENTIFIER NULL

	CONSTRAINT PK_BlogLikes_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90),
	CONSTRAINT FK_BlogLikes_BlogEntityId FOREIGN KEY(BlogEntityId) REFERENCES Blogs(Id)
)
