CREATE TABLE [dbo].[CommentLikes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[CommentId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT PK_CommentLikes_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90),
	CONSTRAINT FK_CommentLikes_CommentId FOREIGN KEY(CommentId) REFERENCES Comments(Id)
)