CREATE TABLE [dbo].[Comments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Content] NVARCHAR(MAX) NULL,
	[BlogEntityId] UNIQUEIDENTIFIER NOT NULL,
	[Status] TINYINT NOT NULL,
	[CommentId] UNIQUEIDENTIFIER NOT NULL,
	[InsertedBy] UNIQUEIDENTIFIER NOT NULL,
	[InsertedDate] DATETIME NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NULL,
	[LastEditedDate] DATETIME NULL,
	[IsDeleted] BIT NULL,
	[DeletedBy] UNIQUEIDENTIFIER NULL,
	[DeletedDate] DATETIME NULL

	CONSTRAINT PK_Comments_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90),
	CONSTRAINT FK_Comments_BlogEntityId FOREIGN KEY(BlogEntityId) REFERENCES Blogs(Id),
	CONSTRAINT FK_Comments_CommentId FOREIGN KEY(CommentId) REFERENCES Comments(Id)
)
