CREATE TABLE [dbo].[Documents]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NULL,
	[FileNameGuid] NVARCHAR(MAX) NULL,
	[FileMimeType] NVARCHAR(MAX) NULL,
	[InsertedBy] UNIQUEIDENTIFIER NOT NULL,
	[InsertedDate] DATETIME NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NULL,
	[LastEditedDate] DATETIME NULL,
	[IsDeleted] BIT NULL,
	[DeletedBy] UNIQUEIDENTIFIER NULL,
	[DeletedDate] DATETIME

	CONSTRAINT PK_Documents_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90)
)
