CREATE TABLE [dbo].[Roles]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(256) NULL,
	[NormalizedName] NVARCHAR(256) NULL,
	[ConcurrencyStamp] NVARCHAR(MAX) NULL,

	CONSTRAINT PK_Roles_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90)
)
