CREATE TABLE [dbo].[RoleClaims]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[RoleId] UNIQUEIDENTIFIER NOT NULL,
	[ClaimType] NVARCHAR(MAX) NULL,
	[ClaimValue] NVARCHAR(MAX) NULL,

	CONSTRAINT PK_RoleClaims_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90),
	CONSTRAINT FK_RoleClaims_RoleId FOREIGN KEY(RoleId) REFERENCES Roles(Id)
)
