CREATE TABLE [dbo].[Tags]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NULL,
	[Description] NVARCHAR(MAX) NULL,
	[InsertedBy] UNIQUEIDENTIFIER NOT NULL,
	[InsertedDate] DATETIME NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NULL,
	[LastEditedDate] DATETIME NULL,
	[IsDeleted] BIT NULL,
	[DeletedBy] UNIQUEIDENTIFIER NULL,
	[DeletedDate] DATETIME NULL

	CONSTRAINT PK_Tags_Id PRIMARY KEY(Id) WITH(FILLFACTOR=90)
)
