CREATE TABLE [dbo].[UserClaims]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[ClaimType] NVARCHAR(MAX) NULL,
	[ClaimValue] NVARCHAR(MAX) NULL

	CONSTRAINT PK_UserClaims_Id PRIMARY KEY(Id) WITH (FILLFACTOR = 90),
	CONSTRAINT FK_UserClaims_UserId FOREIGN KEY(Id) REFERENCES Users(Id)
)
